package com.tongmeng.txyspring.model.hibernate;
// Generated 2016-6-8 14:16:35 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * JobExtraInfo generated by hbm2java
 */
@Entity
@Table(name = "job_extra_info", catalog = "txyspring")
public class JobExtraInfo implements java.io.Serializable {

	private int id;
	private CommonActInfo commonActInfo;
	private String salary;
	private String jobInfo;

	public JobExtraInfo() {
	}

	public JobExtraInfo(CommonActInfo commonActInfo) {
		this.commonActInfo = commonActInfo;
	}

	public JobExtraInfo(CommonActInfo commonActInfo, String salary, String jobInfo) {
		this.commonActInfo = commonActInfo;
		this.salary = salary;
		this.jobInfo = jobInfo;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "commonActInfo"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public CommonActInfo getCommonActInfo() {
		return this.commonActInfo;
	}

	public void setCommonActInfo(CommonActInfo commonActInfo) {
		this.commonActInfo = commonActInfo;
	}

	@Column(name = "Salary", length = 100)
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Column(name = "Job_Info", length = 100)
	public String getJobInfo() {
		return this.jobInfo;
	}

	public void setJobInfo(String jobInfo) {
		this.jobInfo = jobInfo;
	}

}
