package com.tongmeng.txyspring.model;
// Generated 2016-3-14 20:59:07 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActCode generated by hbm2java
 */
@Entity
@Table(name = "act_code", catalog = "txyspring")
public class ActCode implements java.io.Serializable {

	private ActCodeId id;
	private String descriptionSubtype;
	private Set<CommonActInfo> commonActInfos = new HashSet<CommonActInfo>(0);

	public ActCode() {
	}

	public ActCode(ActCodeId id) {
		this.id = id;
	}

	public ActCode(ActCodeId id, String descriptionSubtype, Set<CommonActInfo> commonActInfos) {
		this.id = id;
		this.descriptionSubtype = descriptionSubtype;
		this.commonActInfos = commonActInfos;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "actType", column = @Column(name = "Act_Type", nullable = false)),
			@AttributeOverride(name = "actSubtype", column = @Column(name = "Act_Subtype", nullable = false)) })
	public ActCodeId getId() {
		return this.id;
	}

	public void setId(ActCodeId id) {
		this.id = id;
	}

	@Column(name = "Description_Subtype", length = 100)
	public String getDescriptionSubtype() {
		return this.descriptionSubtype;
	}

	public void setDescriptionSubtype(String descriptionSubtype) {
		this.descriptionSubtype = descriptionSubtype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actCode")
	public Set<CommonActInfo> getCommonActInfos() {
		return this.commonActInfos;
	}

	public void setCommonActInfos(Set<CommonActInfo> commonActInfos) {
		this.commonActInfos = commonActInfos;
	}

}
