package com.tongmeng.txyspring.model;
// Generated 2016-3-16 17:14:58 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActivitiesViewId generated by hbm2java
 */
@Embeddable
public class ActivitiesViewId implements java.io.Serializable {

	private int id;
	private String title;
	private String image;
	private Date startTime;
	private Date endTime;
	private String location;
	private Integer personNum;
	private Integer type;
	private Integer subType;
	private BigDecimal hot;
	private String isActive;
	private String effective;
	private String salary;
	private Date releaseTime;

	public ActivitiesViewId() {
	}

	public ActivitiesViewId(int id, String title, Date startTime, Date endTime, String isActive, String effective,
			String salary, Date releaseTime) {
		this.id = id;
		this.title = title;
		this.startTime = startTime;
		this.endTime = endTime;
		this.isActive = isActive;
		this.effective = effective;
		this.salary = salary;
		this.releaseTime = releaseTime;
	}

	public ActivitiesViewId(int id, String title, String image, Date startTime, Date endTime, String location,
			Integer personNum, Integer type, Integer subType, BigDecimal hot, String isActive, String effective,
			String salary, Date releaseTime) {
		this.id = id;
		this.title = title;
		this.image = image;
		this.startTime = startTime;
		this.endTime = endTime;
		this.location = location;
		this.personNum = personNum;
		this.type = type;
		this.subType = subType;
		this.hot = hot;
		this.isActive = isActive;
		this.effective = effective;
		this.salary = salary;
		this.releaseTime = releaseTime;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "image", length = 65535)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "startTime", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Column(name = "endTime", nullable = false, length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "location", length = 65535)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "personNum")
	public Integer getPersonNum() {
		return this.personNum;
	}

	public void setPersonNum(Integer personNum) {
		this.personNum = personNum;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "subType")
	public Integer getSubType() {
		return this.subType;
	}

	public void setSubType(Integer subType) {
		this.subType = subType;
	}

	@Column(name = "hot", precision = 13, scale = 1)
	public BigDecimal getHot() {
		return this.hot;
	}

	public void setHot(BigDecimal hot) {
		this.hot = hot;
	}

	@Column(name = "isActive", nullable = false, length = 8)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "effective", nullable = false, length = 9)
	public String getEffective() {
		return this.effective;
	}

	public void setEffective(String effective) {
		this.effective = effective;
	}

	@Column(name = "salary", nullable = false, length = 6)
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Column(name = "releaseTime", nullable = false, length = 19)
	public Date getReleaseTime() {
		return this.releaseTime;
	}

	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivitiesViewId))
			return false;
		ActivitiesViewId castOther = (ActivitiesViewId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getImage() == castOther.getImage()) || (this.getImage() != null
						&& castOther.getImage() != null && this.getImage().equals(castOther.getImage())))
				&& ((this.getStartTime() == castOther.getStartTime()) || (this.getStartTime() != null
						&& castOther.getStartTime() != null && this.getStartTime().equals(castOther.getStartTime())))
				&& ((this.getEndTime() == castOther.getEndTime()) || (this.getEndTime() != null
						&& castOther.getEndTime() != null && this.getEndTime().equals(castOther.getEndTime())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
						&& castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())))
				&& ((this.getPersonNum() == castOther.getPersonNum()) || (this.getPersonNum() != null
						&& castOther.getPersonNum() != null && this.getPersonNum().equals(castOther.getPersonNum())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getSubType() == castOther.getSubType()) || (this.getSubType() != null
						&& castOther.getSubType() != null && this.getSubType().equals(castOther.getSubType())))
				&& ((this.getHot() == castOther.getHot()) || (this.getHot() != null && castOther.getHot() != null
						&& this.getHot().equals(castOther.getHot())))
				&& ((this.getIsActive() == castOther.getIsActive()) || (this.getIsActive() != null
						&& castOther.getIsActive() != null && this.getIsActive().equals(castOther.getIsActive())))
				&& ((this.getEffective() == castOther.getEffective()) || (this.getEffective() != null
						&& castOther.getEffective() != null && this.getEffective().equals(castOther.getEffective())))
				&& ((this.getSalary() == castOther.getSalary()) || (this.getSalary() != null
						&& castOther.getSalary() != null && this.getSalary().equals(castOther.getSalary())))
				&& ((this.getReleaseTime() == castOther.getReleaseTime())
						|| (this.getReleaseTime() != null && castOther.getReleaseTime() != null
								&& this.getReleaseTime().equals(castOther.getReleaseTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getImage() == null ? 0 : this.getImage().hashCode());
		result = 37 * result + (getStartTime() == null ? 0 : this.getStartTime().hashCode());
		result = 37 * result + (getEndTime() == null ? 0 : this.getEndTime().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result + (getPersonNum() == null ? 0 : this.getPersonNum().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getSubType() == null ? 0 : this.getSubType().hashCode());
		result = 37 * result + (getHot() == null ? 0 : this.getHot().hashCode());
		result = 37 * result + (getIsActive() == null ? 0 : this.getIsActive().hashCode());
		result = 37 * result + (getEffective() == null ? 0 : this.getEffective().hashCode());
		result = 37 * result + (getSalary() == null ? 0 : this.getSalary().hashCode());
		result = 37 * result + (getReleaseTime() == null ? 0 : this.getReleaseTime().hashCode());
		return result;
	}

}
