package com.tongmeng.txyspring.model;
// Generated 2016-3-16 17:14:58 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActivitiesView generated by hbm2java
 */
@Entity
@Table(name = "activities_view", catalog = "txyspring")
public class ActivitiesView implements java.io.Serializable {

	private ActivitiesViewId id;

	public ActivitiesView() {
	}

	public ActivitiesView(ActivitiesViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "title", column = @Column(name = "title", nullable = false, length = 65535)),
			@AttributeOverride(name = "image", column = @Column(name = "image", length = 65535)),
			@AttributeOverride(name = "startTime", column = @Column(name = "startTime", nullable = false, length = 19)),
			@AttributeOverride(name = "endTime", column = @Column(name = "endTime", nullable = false, length = 19)),
			@AttributeOverride(name = "location", column = @Column(name = "location", length = 65535)),
			@AttributeOverride(name = "personNum", column = @Column(name = "personNum")),
			@AttributeOverride(name = "type", column = @Column(name = "type")),
			@AttributeOverride(name = "subType", column = @Column(name = "subType")),
			@AttributeOverride(name = "hot", column = @Column(name = "hot", precision = 13, scale = 1)),
			@AttributeOverride(name = "isActive", column = @Column(name = "isActive", nullable = false, length = 8)),
			@AttributeOverride(name = "effective", column = @Column(name = "effective", nullable = false, length = 9)),
			@AttributeOverride(name = "salary", column = @Column(name = "salary", nullable = false, length = 6)),
			@AttributeOverride(name = "releaseTime", column = @Column(name = "releaseTime", nullable = false, length = 19)) })
	public ActivitiesViewId getId() {
		return this.id;
	}

	public void setId(ActivitiesViewId id) {
		this.id = id;
	}

}
