package com.tongmeng.txyspring.model;
// Generated 2016-3-14 20:59:07 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PostExtraInfo generated by hbm2java
 */
@Entity
@Table(name = "post_extra_info", catalog = "txyspring")
public class PostExtraInfo implements java.io.Serializable {

	private int id;
	private CommonActInfo commonActInfo;
	private String organizer;
	private String sponsor;

	public PostExtraInfo() {
	}

	public PostExtraInfo(CommonActInfo commonActInfo) {
		this.commonActInfo = commonActInfo;
	}

	public PostExtraInfo(CommonActInfo commonActInfo, String organizer, String sponsor) {
		this.commonActInfo = commonActInfo;
		this.organizer = organizer;
		this.sponsor = sponsor;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "commonActInfo"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public CommonActInfo getCommonActInfo() {
		return this.commonActInfo;
	}

	public void setCommonActInfo(CommonActInfo commonActInfo) {
		this.commonActInfo = commonActInfo;
	}

	@Column(name = "Organizer", length = 100)
	public String getOrganizer() {
		return this.organizer;
	}

	public void setOrganizer(String organizer) {
		this.organizer = organizer;
	}

	@Column(name = "Sponsor", length = 100)
	public String getSponsor() {
		return this.sponsor;
	}

	public void setSponsor(String sponsor) {
		this.sponsor = sponsor;
	}

}
