package com.tongmeng.txyspring.model;
// Generated 2016-3-14 20:59:07 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SchCode generated by hbm2java
 */
@Entity
@Table(name = "sch_code", catalog = "txyspring")
public class SchCode implements java.io.Serializable {

	private SchCodeId id;
	private String description;
	private Set<CommonActInfo> commonActInfos = new HashSet<CommonActInfo>(0);

	public SchCode() {
	}

	public SchCode(SchCodeId id) {
		this.id = id;
	}

	public SchCode(SchCodeId id, String description, Set<CommonActInfo> commonActInfos) {
		this.id = id;
		this.description = description;
		this.commonActInfos = commonActInfos;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "schCode", column = @Column(name = "Sch_Code", nullable = false)),
			@AttributeOverride(name = "areaCode", column = @Column(name = "Area_Code", nullable = false)) })
	public SchCodeId getId() {
		return this.id;
	}

	public void setId(SchCodeId id) {
		this.id = id;
	}

	@Column(name = "Description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schCode")
	public Set<CommonActInfo> getCommonActInfos() {
		return this.commonActInfos;
	}

	public void setCommonActInfos(Set<CommonActInfo> commonActInfos) {
		this.commonActInfos = commonActInfos;
	}

}
