package com.tongmeng.txyspring.model;
// Generated 2016-3-14 20:59:07 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SchCodeId generated by hbm2java
 */
@Embeddable
public class SchCodeId implements java.io.Serializable {

	private int schCode;
	private int areaCode;

	public SchCodeId() {
	}

	public SchCodeId(int schCode, int areaCode) {
		this.schCode = schCode;
		this.areaCode = areaCode;
	}

	@Column(name = "Sch_Code", nullable = false)
	public int getSchCode() {
		return this.schCode;
	}

	public void setSchCode(int schCode) {
		this.schCode = schCode;
	}

	@Column(name = "Area_Code", nullable = false)
	public int getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(int areaCode) {
		this.areaCode = areaCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchCodeId))
			return false;
		SchCodeId castOther = (SchCodeId) other;

		return (this.getSchCode() == castOther.getSchCode()) && (this.getAreaCode() == castOther.getAreaCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSchCode();
		result = 37 * result + this.getAreaCode();
		return result;
	}

}
