package com.tongmeng.txyspring.model;
// Generated 2016-6-8 14:16:35 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserActClt generated by hbm2java
 */
@Entity
@Table(name = "user_act_clt", catalog = "txyspring")
public class UserActClt implements java.io.Serializable {

	private Integer id;
	private CommonActInfo commonActInfo;
	private UserAll userAll;

	public UserActClt() {
	}

	public UserActClt(CommonActInfo commonActInfo, UserAll userAll) {
		this.commonActInfo = commonActInfo;
		this.userAll = userAll;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Act_ID", nullable = false)
	public CommonActInfo getCommonActInfo() {
		return this.commonActInfo;
	}

	public void setCommonActInfo(CommonActInfo commonActInfo) {
		this.commonActInfo = commonActInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_ID", nullable = false)
	public UserAll getUserAll() {
		return this.userAll;
	}

	public void setUserAll(UserAll userAll) {
		this.userAll = userAll;
	}

}
